### ISSUE TITLE
cyanide

### ISSUE THREAD

**Issue by tmirza5** [devraza/hazakura#1]
The cyan is not cyaning
![image](https://github.com/devraza/hazakura/assets/74989523/7a593eb8-9923-413f-b630-8f9a19ca0c2a)

**Comment by devraza** [comment]
Please restrict issues to import discussions, suggestions, or other such things.
If you believe that your issue has met these requirements, then you should work to improve the clarity of your wording and provide more detail.

**Comment by tmirza5** [comment]
This is indeed a relevant issue. You seem to be colourblind, meaning you are deficient in recognising respective colours. This will turn into a bigger issue if not treated. Good luck.

**Comment by devraza** [comment]
I disagree, and your point...is pointless.
